version: 2.1

orbs:
  build-tools: circleci/build-tools@dev:alpha
  orb-tools: circleci/orb-tools@7.3.0

executors:
  macos:
    macos:
      xcode: "10.1.0"

jobs:
  # lint goes here: see workflow
  # validate goes here: see workflow
  # publish-dev goes here: see workflow
  # trigger-integration goes here: see workflow

  # trigger-filtered-run-tests-workflow:
  #   executor: build-tools/ci-base
  #   steps:
  #     - checkout

  #     - add_ssh_keys:
  #         fingerprints:
  #           - 16:68:60:ae:33:5c:4e:b3:be:61:26:ce:9a:f3:ed:84

  #     - run:
  #         name: git config
  #         command: |
  #           git config --global user.name "$CIRCLE_USERNAME"
  #           git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"

  #     - run:
  #         name: push special filtered-run-tests branch
  #         command: |
  #           git checkout -b filtered-run-tests
  #           git push origin filtered-run-tests

  trigger-filtered-run-test-jobs:
    executor: build-tools/ci-base
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - 16:68:60:ae:33:5c:4e:b3:be:61:26:ce:9a:f3:ed:84

      - run:
          name: git config
          command: |
            git config --global user.name "$CIRCLE_USERNAME"
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"

      - run:
          name: push only-branch branch
          command: |
            MAIN_BRANCH="$CIRCLE_BRANCH"
            git checkout -b filtered-run-tests_only-branch
            git push origin filtered-run-tests_only-branch
            git checkout "$MAIN_BRANCH"

      - run:
          name: push ignore-branch branch
          command: |
            MAIN_BRANCH="$CIRCLE_BRANCH"
            git checkout -b filtered-run-tests_ignore-branch
            git push origin filtered-run-tests_ignore-branch
            git checkout "$MAIN_BRANCH"

      - run:
          name: push only-tag tag
          command: |
            git tag filtered-run-tests_only-tag
            git push origin filtered-run-tests_only-tag

      - run:
          name: push ignore-tag tag
          command: |
            git tag filtered-run-tests_ignore-tag
            git push origin filtered-run-tests_ignore-tag

  test-orb-commands:
    executor: build-tools/macos
    steps:
      - checkout

      - build-tools/ensure-command:
          command: brew

      - build-tools/script-run:
          label: set up skeleton filesystem to validate ios-logs command (also test script-run command)
          script: |
            #!/bin/bash

            mkdir -p ~/project/fastlane
            echo fastfile > ~/project/fastlane/Fastfile
            echo gymfile > ~/project/fastlane/Gymfile
            echo appfile > ~/project/fastlane/Appfile

            mkdir -p ~/project/ccidiag.xcodeproj
            echo project > ~/project/ccidiag.xcodeproj/project.pbxproj

      - build-tools/script-run:
          label: validate file init (& test script-run again)
          script: |
            #!/bin/bash

            if [ ! -f ~/project/fastlane/Appfile ]; then
              echo "file init did not succeed"
              exit 1
            else
              echo appfile >> ~/project/fastlane/Appfile
            fi

      # test rest of build-tools commands
      - build-tools/env-info
      - build-tools/ios-logs
      - build-tools/memory
      - build-tools/test-results
      - build-tools/store-report

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [test-orb-commands-master, introspect-orbs-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint:
          filters:
            branches:
              ignore: /filtered-run-tests*/

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: circleci/build-tools
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          ssh-fingerprints: 16:68:60:ae:33:5c:4e:b3:be:61:26:ce:9a:f3:ed:84
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: 16:68:60:ae:33:5c:4e:b3:be:61:26:ce:9a:f3:ed:84
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-deploy:
    jobs:
      # triggered by non-master branch commits
      - test-orb-commands:
          name: test-orb-commands-dev
          filters: *integration-dev_filters

      - build-tools/introspect-orbs:
          name: introspect-orbs-dev
          filters: *integration-dev_filters

      - trigger-filtered-run-test-jobs:
          name: trigger-filtered-run-test-jobs-dev
          filters: *integration-dev_filters

      # triggered by master branch commits
      - test-orb-commands:
          name: test-orb-commands-master
          filters: *integration-master_filters

      - build-tools/introspect-orbs:
          name: introspect-orbs-master
          filters: *integration-master_filters

      - trigger-filtered-run-test-jobs:
          name: trigger-filtered-run-test-jobs-master
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/build-tools
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          release: minor
          context: orb-publishing
          orb-name: circleci/build-tools
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          release: major
          context: orb-publishing
          orb-name: circleci/build-tools
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
